### ISSUE TITLE
Can't run this site on localhost

### ISSUE THREAD

**Issue by LalitNM** [STAC-IITMandi/Blog#15]
Probably `Gemfile.lock` is not updated with latest gems. One example for the same is that, this site is bundled with `bundler 1.16.4` but we have `bundler 2.1.4` now.

**Comment by LalitNM** [comment]
@abhijeetmanhas according to [this](https://talk.jekyllrb.com/t/gemfile-lock-and-git-repos/2519/2), it seems fair to me to commit `Gemfile.lock` on github. What do you think?

**Comment by abhijeetmanhas** [comment]
yes, commit it.
